/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.awt.HeadlessException;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.Connection;
import javax.swing.JOptionPane;


/**
 *
 * @author MFS
 */
public class JerseyShop extends javax.swing.JFrame {
    private void clear_form(){
        txtnojersey.setEditable(true);
        txtnojersey.setText(null);
        txtnamajersey.setText(null);
        cbmerk.setSelectedItem(this);
        txtukuran.setText(null);
        txtjumlah.setText(null);
        txtHsatuan.setText(null);
    }
    
    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("No.Jersey");
        model.addColumn("Nama Jersey");
        model.addColumn("Merk");
        model.addColumn("Ukuran");
        model.addColumn("Jumlah");
        model.addColumn("Harga Satuan");
        
        try{
            int no =1;
            String sql = "SELECT * From jerseyshop";
            java.sql.Connection conn = (Connection)KoneksiSql.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet rslt = stm.executeQuery(sql);
            
            while(rslt.next()){
                model.addRow(new Object[]{no++,rslt.getString(1),rslt.getString(2),rslt.getString(3),rslt.getString(4),rslt.getString(5),rslt.getString(6)});            
            }
            jerseyshop.setModel(model);
            
        } catch (SQLException e){
            System.out.println("Error : " +e.getMessage());
        }
        }
    
    /**
     * Creates new form JerseyShop
     */
    public JerseyShop() {
        initComponents();
        tampilkan_data();
        clear_form();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnojersey = new javax.swing.JTextField();
        txtnamajersey = new javax.swing.JTextField();
        txtukuran = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        cbmerk = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jerseyshop = new javax.swing.JTable();
        tbsimpan = new javax.swing.JButton();
        tbreset = new javax.swing.JButton();
        tbedit = new javax.swing.JButton();
        tbhapus = new javax.swing.JButton();
        tbquit = new javax.swing.JButton();
        txtHsatuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Daftar Barang Jersey Shop");

        jLabel2.setText("No.Jersey");

        jLabel3.setText("Nama Jersey");

        jLabel4.setText("Merk Jersey");

        jLabel5.setText("Ukuran");

        jLabel6.setText("Jumlah");

        txtnojersey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnojerseyActionPerformed(evt);
            }
        });

        txtnamajersey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamajerseyActionPerformed(evt);
            }
        });

        txtukuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtukuranActionPerformed(evt);
            }
        });

        txtjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahActionPerformed(evt);
            }
        });

        cbmerk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adidas", "Nike", "Puma", "NewBalance", "Specs", "Joma", "Umbro" }));
        cbmerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmerkActionPerformed(evt);
            }
        });

        jerseyshop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jerseyshop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jerseyshopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jerseyshop);

        tbsimpan.setText("Simpan");
        tbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbsimpanActionPerformed(evt);
            }
        });

        tbreset.setText("Reset");
        tbreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbresetActionPerformed(evt);
            }
        });

        tbedit.setText("Edit");
        tbedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbeditActionPerformed(evt);
            }
        });

        tbhapus.setText("Hapus");
        tbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbhapusActionPerformed(evt);
            }
        });

        tbquit.setText("Quit");
        tbquit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbquitActionPerformed(evt);
            }
        });

        txtHsatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHsatuanActionPerformed(evt);
            }
        });

        jLabel7.setText("Harga Satuan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))))
                                .addGap(116, 116, 116)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtjumlah)
                                    .addComponent(txtukuran)
                                    .addComponent(txtnamajersey)
                                    .addComponent(txtnojersey)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbmerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtHsatuan)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(tbreset)
                                .addGap(27, 27, 27)
                                .addComponent(tbsimpan)
                                .addGap(18, 18, 18)
                                .addComponent(tbedit)
                                .addGap(18, 18, 18)
                                .addComponent(tbhapus)
                                .addGap(18, 18, 18)
                                .addComponent(tbquit)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(128, 128, 128))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(389, 389, 389))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnojersey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtnamajersey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtukuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbsimpan)
                    .addComponent(tbreset)
                    .addComponent(tbedit)
                    .addComponent(tbhapus)
                    .addComponent(tbquit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnojerseyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnojerseyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnojerseyActionPerformed

    private void txtnamajerseyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamajerseyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamajerseyActionPerformed

    private void txtukuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtukuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtukuranActionPerformed

    private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahActionPerformed

    private void cbmerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmerkActionPerformed

    private void tbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbsimpanActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO jerseyshop VALUES('"+txtnojersey.getText()+"','"+txtnamajersey.getText()+"','"+cbmerk.getSelectedItem()+"','"+txtukuran.getText()+"','"+txtjumlah.getText()+"','"+txtHsatuan.getText()+"')";
            java.sql.Connection conn = (Connection)KoneksiSql.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Proses Penyimpanan Data Barang Berhasil");
            tampilkan_data();
            clear_form();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Penyimpanan Data Gagal");
        }
    }//GEN-LAST:event_tbsimpanActionPerformed

    private void tbresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbresetActionPerformed
        // TODO add your handling code here:
    clear_form();
    }//GEN-LAST:event_tbresetActionPerformed

    private void tbquitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbquitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tbquitActionPerformed

    private void tbeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbeditActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE jerseyshop SET no_jersey='"+txtnojersey.getText()+"',nama_jersey='"+txtnamajersey.getText()+"',merk='"+cbmerk.getSelectedItem()+"',ukuran='"+txtukuran.getText()+"',jumlah='"+txtjumlah.getText()+"',harga_satuan='"+txtHsatuan.getText()+"' WHERE no_jersey = '"+txtnojersey.getText()+"'";
            java.sql.Connection conn = (Connection)KoneksiSql.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil");
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data();
        clear_form();
    }//GEN-LAST:event_tbeditActionPerformed

    private void jerseyshopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jerseyshopMouseClicked
        // TODO add your handling code here:
        int baris = jerseyshop.rowAtPoint(evt.getPoint());
        String no_jersey = jerseyshop.getValueAt(baris,1).toString();
        txtnojersey.setText(no_jersey);
        String nama_jersey = jerseyshop.getValueAt(baris,2).toString();
        txtnamajersey.setText(nama_jersey);
        String merk = jerseyshop.getValueAt(baris,3).toString();
        cbmerk.setSelectedItem(merk);
        String ukuran = jerseyshop.getValueAt(baris,4).toString();
        txtukuran.setText(ukuran);
        String jumlah = jerseyshop.getValueAt(baris,5).toString();
        txtjumlah.setText(jumlah);
        String harga_satuan = jerseyshop.getValueAt(baris,6).toString();
        txtHsatuan.setText(harga_satuan);
        
    }//GEN-LAST:event_jerseyshopMouseClicked

    private void tbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbhapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM jerseyshop WHERE no_jersey = '"+txtnojersey.getText()+"'";
            java.sql.Connection conn = (Connection)KoneksiSql.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
        } catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data();
        clear_form();
    }//GEN-LAST:event_tbhapusActionPerformed

    private void txtHsatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHsatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHsatuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JerseyShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JerseyShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JerseyShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JerseyShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JerseyShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbmerk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jerseyshop;
    private javax.swing.JButton tbedit;
    private javax.swing.JButton tbhapus;
    private javax.swing.JButton tbquit;
    private javax.swing.JButton tbreset;
    private javax.swing.JButton tbsimpan;
    private javax.swing.JTextField txtHsatuan;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtnamajersey;
    private javax.swing.JTextField txtnojersey;
    private javax.swing.JTextField txtukuran;
    // End of variables declaration//GEN-END:variables
}
